metros = float(input('Digite o tamanho em metros:'))
dam = (metros / 10)
cm = (metros * 100)
mm = (metros * 1000)
dm = (metros * 10)
hm = (metros / 100)
km = (metros / 1000)
print('A medida de {}m corresponde a:\n{}km\n{}hm\n{}dam\n{}dm\n{}cm\n{}mm '.format(metros, km, hm, dam, dm, cm, mm))
