tabu = int(input('Digite o número que você deseja a tabuada: '))
#rint('{}* 1 =',tabu*1, '{}* 2 =', tabu * 2, '{}*3 =',tabu*3, '{}* 4 =',tabu*4,'*2'.format(tabu, tabu, tabu))
print('{} * {:2} = {}'.format(tabu, '1', tabu))
print('{} * {:2} = {}'.format(tabu, '2', tabu * 2))
print('{} * {:2} = {}'.format(tabu, '3', tabu * 3))
print('{} * {:2} = {}'.format(tabu, '4', tabu * 4))
print('{} * {:2} = {}'.format(tabu, '5', tabu * 5))
print('{} * {:2} = {}'.format(tabu, '6', tabu * 6))
print('{} * {:2} = {}'.format(tabu, '7', tabu * 7))
print('{} * {:2} = {}'.format(tabu, '8', tabu * 8))
print('{} * {:2} = {}'.format(tabu, '9', tabu * 9))
print('{} * {:2} = {}'.format(tabu, '10', tabu * 10))
