numero = int(input('Digite um número:'))
unidade = (numero % 10)
dezena = ((numero % 100)//10)
centena = ((numero % 1000) // 100)
# milhar = (numero // 1000)
milhar = ((numero % 10000) // 1000)
print('Unidade:{}'.format(unidade))
print('Dezena:{:.0f}'.format(dezena))
print('Centena:{:.0f}'.format(centena))
print('Milhar:{:.0f}'.format(milhar))
