print('~~'*20)
print('CALCULO DO PREÇO TETO DE UMA AÇÃO')
print('~~'*20)
codigo = str(input('Digite o ticker:'))
print('EXERCICIO DOS ÚLTIMOS 5 ANOS')
ano1 = float(input('Proventos distribuidos no 1° ano:'))
ano2 = float(input('Proventos distribuidos no 2° ano:'))
ano3 = float(input('Proventos distribuidos no 3° ano:'))
ano4 = float(input('Proventos distribuidos no 4° ano:'))
ano5 = float(input('Proventos distribuidos no 5° ano:'))
calculo = ((ano1 + ano2 + ano3 + ano4 + ano5)/5)
print('DY requerido 6% Preço teto R${:.2f}'.format(calculo / 0.06))
print('DY requerido 7% Preço teto R${:.2f}'.format(calculo / 0.07))
print('DY requerido 8% Preço teto R${:.2f}'.format(calculo / 0.08))
print('DY requerido 9% Preço teto R${:.2f}'.format(calculo / 0.09))
print('DY requerido 10% Preço teto R${:.2f}'.format(calculo / 0.10))
